### ISSUE TITLE
Proper handling of only_own_events (will enrich on pc) 

### ISSUE THREAD

**Issue by TonnyMunkNielsen** [mkotler/ad-automoli#12] opened 2024-02-11 09:27 UTC
😩 **Describe the issue/bug**
The description of _only_own_events=True_ state:

> "Lights will only be turned off after motion is detected, if AutoMoLi turned the lights on."

This sequence of events occurred in my house:

1. I go through the hallway into the laundry room triggering the motion sensor located in the hallway - This turns on the lights in the laundry room.
2. I press my smart switch to first turn off and then turn on the laundry room lights manually.
3. I exit the laundry room through the hallway.
4. The laundry room lights turn off after the 10 second delay configured.

😒 **Expected behavior**
I expect that manually turning off and then turning on the lights in the laundry room will "override" the initial motion sensor event, and thus, due to only_own_events being True, it should recognize that the last state change of the lights was not caused by AutoMoLi, and this be ignored.

🎛️ **Configuration**
```yaml
light_automation_laundry_room:
  module: automoli
  class: AutoMoLi
  log: light_automation_laundry_room
  room: laundry_room

  motion_state_on: "on"
  motion_state_off: "off"

  disable_hue_groups: true
  only_own_events: true

  delay: 10
  # delay_outside_events: 0

  # Default workaround to fail in https://github.com/benleb/ad-automoli/issues/87#issue-1014478987, not sure if this is present on the mkotler fork.
  daytimes:
    - { starttime: "05:30", name: "morning", light: 25 }
    - { starttime: "07:30", name: "day", light: 100 }
    - { starttime: "20:30", name: "evening", light: 90 }
    - { starttime: "22:30", name: "night", light: 50 }

  # You can specify a light group or list of lights here
  lights:
    - light.laundry_room_lights

  # You can specify a list of motion sensors here
  motion:
    - binary_sensor.presence_hallway

  debug_log: true
```

🧠 **System**
 - AppDaemon: **4.4.2**
   -  running mode: **docker**
 - Home-Assistant: **2024.1.6**
   -  running mode: **docker**
 - Python: **3.10.11**

🗒️ **Logs** 

```log
2024-02-11 15:34:33.225084 INFO light_automation_laundry_room:  clear_handles: cancelled scheduled callbacks
2024-02-11 15:34:33.226078 INFO light_automation_laundry_room:  refresh_timer: self.active = {'daytime': 'day', 'delay': 10, 'starttime': '07:30:00', 'light_setting': 100, 'is_hue_group': False} | self.delay_outside_events = 10 | outside_change = False | delay = 10 | self.dim = {}
2024-02-11 15:34:33.227963 INFO light_automation_laundry_room:  refresh_timer: scheduled callback to switch off the lights in 0s at(2024-02-11T15:34:43.226524) | handles: self.room.handles_automoli = {'a2ff848c09c04b419e5370f2a26759c5'}
2024-02-11 15:34:43.230102 INFO light_automation_laundry_room:  lights_off: await self.is_disabled() = False | await self.is_blocked() = False
2024-02-11 15:34:43.232098 INFO light_automation_laundry_room:  clear_handles: cancelled scheduled callbacks
2024-02-11 15:34:43.233729 INFO light_automation_laundry_room:  lights_off: any([await self.get_state(entity) == 'on' for entity in self.lights]) = False | self.lights = ['light.laundry_room_lights']
2024-02-11 15:37:25.080048 INFO light_automation_laundry_room:  motion_detected: binary_sensor.presence_hallway changed state from off to on
2024-02-11 15:37:25.081415 INFO light_automation_laundry_room:  clear_handles: cancelled scheduled callbacks
2024-02-11 15:37:25.082652 INFO light_automation_laundry_room:  motion_detected: handles cleared and cancelled all scheduled timers | self.dimming = False
2024-02-11 15:37:25.084179 INFO light_automation_laundry_room:  motion_event: received '[1mmotion_state_changed_detection[0m' event from 'binary_sensor.presence_hallway' | self.dimming = False
2024-02-11 15:37:25.085531 INFO light_automation_laundry_room:  motion_event: await self.is_disabled() = False | self.dimming = False
2024-02-11 15:37:25.091832 INFO light_automation_laundry_room:  motion_event: switching on | self.dimming = False
2024-02-11 15:37:25.093215 INFO light_automation_laundry_room:  lights_on: self.thresholds.get(EntityType.ILLUMINANCE.idx) = None | self.dimming = False | force = False | bool(force or self.dimming) = False
2024-02-11 15:37:25.097471 INFO light_automation_laundry_room: 💡 [1mLaundry_room[0m turned [1mon[0m → brightness: [1m100[0m% | delay: [1m[1m10[0msec[0m
2024-02-11 15:37:55.246608 INFO light_automation_laundry_room:  motion_cleared: binary_sensor.presence_hallway changed state from on to off
2024-02-11 15:37:55.252227 INFO light_automation_laundry_room:  clear_handles: cancelled scheduled callbacks
2024-02-11 15:37:55.253110 INFO light_automation_laundry_room:  refresh_timer: self.active = {'daytime': 'day', 'delay': 10, 'starttime': '07:30:00', 'light_setting': 100, 'is_hue_group': False} | self.delay_outside_events = 10 | outside_change = False | delay = 10 | self.dim = {}
2024-02-11 15:37:55.257149 INFO light_automation_laundry_room:  refresh_timer: scheduled callback to switch off the lights in 0s at(2024-02-11T15:38:05.253868) | handles: self.room.handles_automoli = {'d0c485c5085140828a5edf60a6c531d4'}
2024-02-11 15:38:05.260294 INFO light_automation_laundry_room:  lights_off: await self.is_disabled() = False | await self.is_blocked() = False
2024-02-11 15:38:05.262215 INFO light_automation_laundry_room:  clear_handles: cancelled scheduled callbacks
2024-02-11 15:38:05.263648 INFO light_automation_laundry_room:  lights_off: any([await self.get_state(entity) == 'on' for entity in self.lights]) = True | self.lights = ['light.laundry_room_lights']
2024-02-11 15:38:05.267672 INFO light_automation_laundry_room:  clear_handles: cancelled scheduled callbacks
2024-02-11 15:38:05.268423 INFO light_automation_laundry_room: 🌑 no motion in [1mLaundry_room[0m since [1m[1m10[0msec[0m → turned [1moff[0m
```

🧁 **Additional context**
My initial thoughts regarding the solution are:

Canceling timers whenever outside events occur, regardless of only_own_events, either independently of the current code, or by changing outside_change_detected to always be triggered here and then modifying the outside_change_detected method itself to fix the bug:
```Python
# set up state listener for each light, if tracking events outside automoli
        if self.only_own_events == False:
            self.lg(
                "handling events outside AutoMoLi - adding state listeners for lights",
                level=logging.DEBUG,
            )
            for light in self.lights:
                listener.add(
                    self.listen_state(
                        self.outside_change_detected,
                        entity_id=light,
                        new="on",
                    )
                )
                # assume any lights that are currently on were switched on by AutoMoLi
                if await self.get_state(light) == "on":
                    self._switched_on_by_automoli.add(light)
```

Perhaps just removing the lights from _switched_on_by_automoli whenever outside events occur, regardless of only_own_events?

I would love feedback on these thoughts.

**Comment by TonnyMunkNielsen** [comment] 2024-02-11 11:40
Still plan to enrich this, but I think that maybe a workaround is touse only_own_events = None and outside_change_delay = 0

**Comment by TonnyMunkNielsen** [comment] 2024-02-11 14:56
@mkotler Please review and I would love to hear your thoughts on this issue. I'm still too green in this particular script to be confident in my solution approach.

**Comment by TonnyMunkNielsen** [comment] 2024-02-11 14:57
Oh, and I'm on your 'dev' branch.

**Comment by mkotler** [comment] 2024-02-11 18:12
@TonnyMunkNielsen: I just checked in a fix in the issue12 branch.  It worked in my testing but want to confirm before I merge it into dev.  

A few notes:  
1) On the fix - Thank you for the analysis and suggestions.  Always triggering outside changes felt like the safer change and had the benefit of being able to track only_own_events = True in statistics.  

2) Dev vs. Main branch - When I started working on AutoMoLi, I was hoping to merge everything back into benleb's version so I made all changes in the dev branch.  Unfortunately, his version wasn't in active development and my fork got further and further out of sync.  I'm now tempted to just merge everything back in to main (also note I just renamed that branch from master) but just haven't taken that step yet.  

3) delay_outside_events - The reason I didn't realize this stopped working is because I switched from using only_own_events to delay_outside_events.  If you want to give it a try, this property allows you to set a different timer when you manually turn on the lights.  For example, for my upstairs hall, if I'm just walking through I set the delay to 3 min.  But if I turn the lights on manually, I set the delay to 20 minutes.

**Comment by TonnyMunkNielsen** [comment] 2024-02-11 18:41
Thank you, I will look at it when I can.

Replies:

1. Agreed.
2. I say go for it, but it's your decision :)
3. Based on this, it sounds like only_own_events is completely redundant? - would the equivalent not just be to set delay_outside_events to 0, and then they could be ignored?

**Comment by TonnyMunkNielsen** [comment] 2024-02-11 20:07
@mkotler

**Comment by mkotler** [comment] 2024-02-12 00:38
#2 - I took the plunge.  With the exception of the change in the issue12 branch, main is up to date with dev
#3 - Yes, delay_outside_events to 0 _should_ behave the same. Let me know if you have a chance to test. But there's a little additional surgery that would be needed to fully remove only_own_events. Saving that for another day.

**Comment by TonnyMunkNielsen** [comment] 2024-02-26 22:27
It seems to work for own_events_only=true! :D


However, I feel like the detection of outside events such as turning off the lights should also cancel timers if "outside_delay" is used rather than own_events_only - And it doesn't seem to :/

Let me know if I'm not explaining this properly, or if you need any details.

**Comment by mkotler** [comment] 2024-02-28 03:18
@TonnyMunkNielsen, I am not sure I am following the specific bug.  outside_delay only changes the delay for turning the lights off.  What is a case where not cancelling the timers when you turn the light off manually has an impact on the behavior?

**Comment by TonnyMunkNielsen** [comment] 2024-02-28 06:15
The scenario is that I walk through the hallway (where the sensor is) to the laundry room, and turn off and on the light manually before the sensor turns from "motion detected" to "no motion". Whenever a manual action is taken, it should override the automatic timers, if outside_delay is on. I see no downsides to my suggestion, but I am always open to gain some more knowledge :)

**Comment by mkotler** [comment] 2024-02-28 09:52
Above when you said it only works when own_events_only is true did you actually mean it only works when it is false? 

I think the timers are actually getting cleared but the problem may be that I don't track lights manually if own_events_only is true but you are using delay_outside_events.  Does that sound right?

**Comment by TonnyMunkNielsen** [comment] 2024-03-01 20:00
I mean, I tested the scenario above for own_events_only=true, then the manual turning off and on did cancel the automatic timer, but when own_events_only=false and a outside_delay declared instead, then the interrupt didn't register.

I'm not saying that manual event don't get tracked at all, the problem is, that if the motion sensor is activated and then the manual event triggered before the motion sensor is cleared, then no manual interrupt is detected (unlike for own_events_only=true on the issue 11 branch).

If I wait until the motion is cleared and then trigger the manual event, then it works okay for outside_delay.

Sorry if I was not being clear.

**Comment by TonnyMunkNielsen** [comment] 2024-03-01 20:18
If you disagree, then I'll see if I can reproduce and paste some debug logs.

**Comment by mkotler** [comment] 2024-03-02 23:15
After trying to reproduce your issue, I think I discovered the problem and it is a really good bug that has been around for a long time.  I introduced (hidden from the documentation) one other feature when I added support for events outside AutoMoli, a cooldown period.  The cooldown period (30 seconds) prevents AutoMoLi from turning the lights back on right away, if they were turned off manually.  

However, I forgot to cancel the cooldown period if you turn the lights back on manually during the cooldown period.  So you turned the lights off and on right away, you were almost certainly still in the 30 second period so it looks like the manual delay didn't have any effect.  What is really nasty about this bug is that it can leave the lights on forever (or at least until another motion is detected).   

I've updated the branch with a fix for this issue and I also made the cooldown period configurable and added it to the documentation.  Please let me know if this fixes the behavior you saw.

**Comment by TonnyMunkNielsen** [comment] 2024-03-04 19:49
Will do, I will report back when I get the time to test it. 

Btw. I think your commitment to this project is commendable! - I feel this engagement is infectious (in a good way).

**Comment by mkotler** [comment] 2024-03-16 17:37
Merged back into main and marking as closed but please reopen is your testing uncovers any issues!

**Closed by mkotler** 2024-03-16 17:37 UTC
